services:
  minecraft:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    stop_grace_period: "1m"
    container_name: minecraft-server
    ports:
      - "25565:25565"
      - "19132:19132/udp"
      - "19133:19133/udp"
      - "24454:24454/udp"

    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      MAX_MEMORY: "4096M"
      MOTD: "TEJAAAAS WORLD"
      ONLINE_MODE: "false"
      USE_AIKAR_FLAGS: "true"
      USE_MEOWICE_FLAGS: "true"
      TZ: "Asia/Kolkata"
      DIFFICULTY: "2"
      VIEW_DISTANCE: "10"
      SIMULATION_DISTANCE: "8"
      MODRINTH_PROJECTS: |-
        ferrite-core
        lithium
        appleskin
        simple-voice-chat
        clumps
        ore-harvester
        tree-harvester
        krypton
        villager-names-serilum
        rightclickharvest
        easyauth
        your-items-are-safe
        c2me-fabric
        inventory-sorting
        skinrestorer
        no-dim
        badpackets

        flower-mimics
        universal-enchants
        upgraded-mobs
        server-side-horror
        chunky
        katters-structures

        oh-the-biomes-weve-gone
        enchantments-encore
        more-armor-trims
        enchantment-lore
        dungeons-and-taverns
        nullscape

      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      ENFORCE_SECURE_PROFILE: "false"
      RCON_CMDS_STARTUP: |-
        gamerule players_sleeping_percentage 1
      BUG_REPORT_LINK: "https://github.com/pranaovs/minecraft-server-docker"
      LOG_TIMESTAMP: "true"

    restart: always

    volumes:
      - "./data:/data:U"
